buttons:
  A: 0
  B: 1
  X: 2
  Y: 3
  LB: 4
  RB: 5
  back: 6
  start: 7
  power: 8
  Left_Stick_Button: 9
  Right_Stick_Button: 10
axes:
  directional_pads:
    Horizontal_Directional_Pad: 6
    Vertical_Directional_Pad: 7
  sticks:
    Horizontal_Left_Stick: 0
    Vertical_Left_Stick: 1
    Horizontal_Right_Stick: 3
    Vertical_Right_Stick: 4
  triggers:
    LT: 2
    RT: 5
